#define CORE_ID 0x126
#define CORE_IRQMAPPER  0x82
#define CORE_LOCK	0x98
#define CORE_STATUS     0x80
#define CORE_UNLOCK	0x99
#define HDA_CMDREG	0x3F6
#define HDA_DATAREGS 	0x110
#define HDA_IRQ 	14
#define HDA_MAXCYLINDER  1024
#define HDA_MAXSECTOR    32
#define HDA_SECTORSIZE   512
#define MAXVOL 8
#define MAX_CORE        16
#define TIMER_ALARM     0xF8
#define TIMER_CLOCK     0xF0
#define TIMER_IRQ       2
#define TIMER_PARAM     0xF4
